Add Unwrap derive (#161)
```rust
#[derive(::derive_more::Unwrap)]
enum Lol {
    Haha(i32),
    Hm,
}

fn main() {
    let a = Lol::Haha(10);
    println!("Results: {:?}", a.unwrap_haha())
}
```
prints `Results: 10`, and switching to `a.unwrap_hm()` prints this message:
> thread 'main' panicked at 'called `Lol::unwrap_hm()` on a `Haha` value', src/main.rs:18:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace