Fix order sensitivity of `Display` attributes (#320, #319)
## Synopsis

See https://github.com/JelteF/derive_more/issues/319#issue-2004684216:

> The following code used to work in 1.0.0-beta.3:
> 
> ```rust
> #[derive(Display)]
> #[display("{name}@{tag}")]
> #[display(bound(Tag: std::fmt::Display))]
> struct Specifier<Tag> {
>     name: String,
>     tag: Tag,
> }
> ```
> 
> However, in 1.0.0-beta.6, it emits the following error message:
> 
> ```
> error: multiple `#[display("...", ...)]` attributes aren't allowed
> ```
> 
> It took me a long time to figure out that the fix was to swap place
between the 2 display attributes.

The regression lies
[here](https://github.com/JelteF/derive_more/blob/v1.0.0-beta.6/impl/src/fmt/mod.rs#L394-L399),
where `mem::replace` doesn't provide the implied and expected "and"
logic for merging two `Option`s.



## Solution

- Merge those two `Option`s correctly.
- Recheck similar places over the code.