Implement `Eq` derive (#479, #163)
Part of #163

## Synopsis

As our `PartialEq` derive infers trait bounds correctly for generic
cases, we need also an `Eq` derive for doing the same.

## Solution

`derive(Eq)` in `std` uses `core::cmp::AssertParamIsEq` to assert that
fields' types are indeed `Eq` in its `Eq::assert_receiver_is_total_eq()`
method. However, they both are `#[doc(hidden)]` and not a stable part of
`std`, so we cannot reuse them blindly.

However, instead, we could just put the appropriate trait bounds in the
`where` clause of the generated `Eq` `impl`:
```rust
impl Eq for Foo where FieldType: Eq {}
```

The only situation where this fails is when the field type uses the
self-type recursively:
```rust
struct Foo(Option<Box<Foo>>);
```
In this case, we cannot generate `Option<Box<Foo>>: Eq` trait bound,
because will hit the compilation error:
```
error[E0275]: overflow evaluating the requirement
```
For such fields, we need to do the similar static assertion as `std`
does, that's why introduce our own
`derive_more::__private::AssertParamIsEq` helper type. In contrast with
`std`, we do generate these assertions (if needed) in an inherent
method, rather than introducing a trait for it.